image: docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - env
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest \
          --build-arg COMPOSER_MAGENTO_USERNAME=$COMPOSER_MAGENTO_USERNAME \
          --build-arg COMPOSER_MAGENTO_PASSWORD=$COMPOSER_MAGENTO_PASSWORD \
          --build-arg COMPOSER_GITHUB_TOKEN=$COMPOSER_GITHUB_TOKEN \
          --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA \
          --tag $CI_REGISTRY_IMAGE:latest \
          .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  tags:
    - docker
