name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/docker-magento2

jobs:

  build-php73-apache:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build 7.3-apache --tag ${{ env.IMAGE }}:7.3 --build-arg COMPOSER_MAGENTO_USERNAME=${{ secrets.COMPOSER_MAGENTO_USERNAME }} --build-arg COMPOSER_MAGENTO_PASSWORD=${{ secrets.COMPOSER_MAGENTO_PASSWORD }} --build-arg M2SETUP_VERSION=2.3.5p1 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to Docker Hub
      run: docker push ${{ env.IMAGE }}:7.3

  build-php74-apache:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build 7.4-apache --tag ${{ env.IMAGE }}:7.4 --build-arg COMPOSER_MAGENTO_USERNAME=${{ secrets.COMPOSER_MAGENTO_USERNAME }} --build-arg COMPOSER_MAGENTO_PASSWORD=${{ secrets.COMPOSER_MAGENTO_PASSWORD }} --build-arg M2SETUP_VERSION=2.4.0 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to Docker Hub
      run: docker push ${{ env.IMAGE }}:7.4

  build-php81-apache:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build 8.1-apache --tag ${{ env.IMAGE }}:8.1 --build-arg COMPOSER_MAGENTO_USERNAME=${{ secrets.COMPOSER_MAGENTO_USERNAME }} --build-arg COMPOSER_MAGENTO_PASSWORD=${{ secrets.COMPOSER_MAGENTO_PASSWORD }} --build-arg M2SETUP_VERSION=2.4.4
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to Docker Hub
      run: docker push ${{ env.IMAGE }}:8.1

  build-php82-apache:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build 8.2-apache --tag ${{ env.IMAGE }}:8.2 --build-arg COMPOSER_MAGENTO_USERNAME=${{ secrets.COMPOSER_MAGENTO_USERNAME }} --build-arg COMPOSER_MAGENTO_PASSWORD=${{ secrets.COMPOSER_MAGENTO_PASSWORD }} --build-arg M2SETUP_VERSION=2.4.6
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to Docker Hub
      run: docker push ${{ env.IMAGE }}:8.2

  build-php83-apache:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build 8.3-apache --tag ${{ env.IMAGE }}:8.3 --build-arg COMPOSER_MAGENTO_USERNAME=${{ secrets.COMPOSER_MAGENTO_USERNAME }} --build-arg COMPOSER_MAGENTO_PASSWORD=${{ secrets.COMPOSER_MAGENTO_PASSWORD }} --build-arg M2SETUP_VERSION=2.4.7
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to Docker Hub
      run: docker push ${{ env.IMAGE }}:8.3
